AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - '*.gemspec'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

# TODO: Figure out how to do this without URI.encode
Lint/UriEscapeUnescape:
  Enabled: false

# Screens are big, even when they're small
Metrics/LineLength:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ClassAndModuleChildren:
  Exclude:
    - '**/*_test.rb'
Metrics/MethodLength:
  Max: 18
  Exclude:
    - '**/*_test.rb'

# Namespace blocks contain multiple tasks
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'

# TODO: Refactor to reduce this
Metrics/AbcSize:
  Max: 26
